name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  on_process_button_widget: ^2.0.3
  package_info_plus: ^8.0.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.5
  http: ^1.2.1
  intl: ^0.19.0
  tuple: ^2.0.2
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/animation/
